### ISSUE TITLE
Missing format name in the content of DocumentReference 

### ISSUE THREAD

**Issue by lennart-bos** [usnistgov/asbestos#129]
The comprehensive PDB request contains the following content:
```
"format": {
  "system": "http://ihe.net/fhir/ValueSet/IHE.FormatCode.codsystem",
  "code": "urn:ihe:pcc:cm:2008"
}
```
Besides the typo in `codsystem`, it is missing the `display` attribute. In pure FHIR, this is an optional attribute (see https://www.hl7.org/fhir/datatypes.html#Coding). However, when dealing with XDS underneath, it is mandatory. See section 4.2.3.1.2 of https://www.ihe.net/uploadedFiles/Documents/ITI/IHE_ITI_TF_Vol3.pdf:

>  Three details are **required** to describe a coded value:
> 1. Code Value – contains the assigned value of the code.
> 2. Code Display Name - The display name used to represent the code (code values are not necessarily human-friendly). Must be **non-zero** length.
> 3. Coding Scheme - An identifier of the coding scheme that the code comes from

**Comment by skbhaskarla** [comment]
While it is correct that the IHE XDS profile requires the code display name, the IHE MHD profile does not indicate any special requirement on the code display name, so the default optionality of the pure HL7 FHIR standard is followed.

**Comment by lennart-bos** [comment]
Thanks for the fast response! I think you are absolutely right for the "minimal" test set. However, isn't the aim of the "comprehensive" option to fulfil the underlying cardinality requirements of XDS?

**Comment by skbhaskarla** [comment]
The testing tool document recipient actor deduced the coding `display` value based on the supplied `system` and `code` since it was aware of the code system in use and it had sufficient information to do so. If the actor was not aware of the code system, then the `display` value would be vital. This is due to the language in HL7 FHIR "The `display` is a text representation of the code defined by the `system` and is used to display the meaning of the code by an application that is not aware of the system." (http://hl7.org/fhir/datatypes.html#Coding)

However, I can add the `display` value according to the IHE reference in the original post and also IHE ITI TF-3 4.2.3.1.2 Creating Coded Attributes
The displayName is a convenience provided by the actor that creates the metadata (“metadata creator”).
